//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAttendance.Resources.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeRex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public EmployeeRex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRAttendance.Resources.Employee.EmployeeRex", typeof(EmployeeRex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LB_Address {
            get {
                return ResourceManager.GetString("LB_Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LB_Email {
            get {
                return ResourceManager.GetString("LB_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Registration.
        /// </summary>
        public static string LB_EMP_REG {
            get {
                return ResourceManager.GetString("LB_EMP_REG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string LB_EMPLOYEE {
            get {
                return ResourceManager.GetString("LB_EMPLOYEE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string LB_Female {
            get {
                return ResourceManager.GetString("LB_Female", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string LB_Gender {
            get {
                return ResourceManager.GetString("LB_Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string LB_ID {
            get {
                return ResourceManager.GetString("LB_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string LB_Male {
            get {
                return ResourceManager.GetString("LB_Male", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Management Permission.
        /// </summary>
        public static string LB_ManagementPermission {
            get {
                return ResourceManager.GetString("LB_ManagementPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LB_Name {
            get {
                return ResourceManager.GetString("LB_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NRC.
        /// </summary>
        public static string LB_NRC {
            get {
                return ResourceManager.GetString("LB_NRC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LB_Password {
            get {
                return ResourceManager.GetString("LB_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string LB_Permission {
            get {
                return ResourceManager.GetString("LB_Permission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LB_Phone {
            get {
                return ResourceManager.GetString("LB_Phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string LB_RegistDate {
            get {
                return ResourceManager.GetString("LB_RegistDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string LB_Shift {
            get {
                return ResourceManager.GetString("LB_Shift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string LB_UserID {
            get {
                return ResourceManager.GetString("LB_UserID", resourceCulture);
            }
        }
    }
}
