//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAttendance.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CommonMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRAttendance.Resources.Common.CommonMessage", typeof(CommonMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted..
        /// </summary>
        public static string MSG_Deleted {
            get {
                return ResourceManager.GetString("MSG_Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid character count. [{0}].
        /// </summary>
        public static string MSG_InvalidCharCount {
            get {
                return ResourceManager.GetString("MSG_InvalidCharCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input value is invalid. [{0}].
        /// </summary>
        public static string MSG_InvalidEnterValue {
            get {
                return ResourceManager.GetString("MSG_InvalidEnterValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string MSG_InvalidRequest {
            get {
                return ResourceManager.GetString("MSG_InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input value is invalid..
        /// </summary>
        public static string MSG_InvalidValue {
            get {
                return ResourceManager.GetString("MSG_InvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password and Confirm password are not same..
        /// </summary>
        public static string MSG_MismatchPasswords {
            get {
                return ResourceManager.GetString("MSG_MismatchPasswords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record is registered/updated successfully..
        /// </summary>
        public static string MSG_Success {
            get {
                return ResourceManager.GetString("MSG_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty. [{0}].
        /// </summary>
        public static string MSG_ValueEmpty {
            get {
                return ResourceManager.GetString("MSG_ValueEmpty", resourceCulture);
            }
        }
    }
}
