//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string ConfigKey { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string StrVal { get; set; }
        public Nullable<double> FloatVal { get; set; }
    }
}
