//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> LastUpdatePasswordDateTime { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<int> DelFlg { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public Nullable<int> DeleteUserID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
